### ISSUE TITLE
Future and maintainer? The advantages over the current reference system ARCGIS?

### ISSUE THREAD

**Issue by steviewanders** [HakaiInstitute/hakai-reference-stations#5]

**Comment by fostermh** [comment]
The advantage of maintaining a station list here, as apposed to AGOL or RDS, is that it is easily accessible by server side code and can contain stations outside of either the EIMS or AGOL systems. Some stations are not public and thus should not be accessible to the AGOL feature layer.

Ideally, we would have one source of truth. importing a csv or json file into Postgres would be easy however updating a feature layer in AGOL is a bit more work.

This discussion and ERSI link may prove useful if we descied to go the 1 source of truth root.
- https://community.esri.com/t5/arcgis-online-questions/update-a-csv-hosted-feature-service-in-agol/td-p/400408
- https://developers.arcgis.com/python/samples/overwriting-feature-layers/

**Comment by steviewanders** [comment]
> The advantage of maintaining a station list here, as apposed to AGOL or RDS, is that it is easily accessible by server side code and can contain stations outside of either the EIMS or AGOL systems. Some stations are not public and thus should not be accessible to the AGOL feature layer.

Makes sense, thanks for explaining.

> Ideally, we would have one source of truth. importing a csv or json file into Postgres would be easy however updating a feature layer in AGOL is a bit more work.

I had this same thought initially but now I'm not sure how ideal it is. For example, your point above about operating on different sets of information and access control. Perhaps we can use that above linked code to extract their reference set instead and go from there. Which stations are not public?

**Comment by fostermh** [comment]
> Perhaps we can use that above-linked code to extract their reference set instead and go from there

that could work, yes.

> Which stations are not public?

All the nature trust sites are one example. There are likely others.
